os: Visual Studio 2015

environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: nightly-2017-03-14
      target: x86_64-pc-windows-msvc

matrix:
  allow_failures:
    - channel: stable

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo build --verbose %cargoflags%
  - cargo build --features="experimental" --verbose
  - cargo test -- --nocapture
  - cargo test --features="experimental" -- --nocapture
  - cargo test --features="scoped_dictionary" -- --nocapture
  - cargo test --features="static_module_dispatch" -- --nocapture
  - cargo run --bin pumpkindb-doctests
  - cargo run --bin pumpkindb-doctests --features="experimental"
  - cargo run --bin pumpkindb-doctests --features="static_module_dispatch"
